version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - /home/ubuntu/financial_backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # This points to the .env file for environment variables