version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: database-1
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: Blockhouse123456789

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dbuser:Blockhouse123456789@db:5432/database-1
    env_file:
      - .env

volumes:
  postgres_data:
