name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t sdshah05/financial-full-stack:${{ github.sha }} .
        docker tag sdshah05/financial-full-stack:${{ github.sha }} sdshah05/financial-full-stack:latest
        docker push sdshah05/financial-full-stack:${{ github.sha }}
        docker push sdshah05/financial-full-stack:latest

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
            cd /home/ubuntu/financial_backend
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
      env:  # Pass GitHub Secrets as environment variables
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
