name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # The workflow triggers when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The CI/CD job runs on an Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the latest code from the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image to DockerHub
      run: |
        docker build -t your_dockerhub_username/django-app:latest .  # Build the Docker image
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  # Log in to DockerHub
        docker push your_dockerhub_username/django-app:latest  # Push the Docker image to DockerHub

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2 public IP or domain
        username: ${{ secrets.EC2_USER }}  # EC2 user (e.g., ubuntu)
        key: ${{ secrets.EC2_PRIVATE_KEY }}  # EC2 private SSH key
        script: |
          cd /path/to/your/app/on/ec2  # Navigate to the directory where docker-compose.yml is located
          docker pull your_dockerhub_username/django-app:latest  # Pull the latest image from DockerHub
          docker-compose down  # Stop any existing containers
          docker-compose up -d --build  # Rebuild and start the containers
